const ActionTypes = {
    GET_HOTEL_REQUEST: "GET_HOTEL_REQUEST",
    GET_HOTEL_SUCCESS: "GET_HOTEL_SUCCESS",
    GET_HOTEL_FAIL: "GET_HOTEL_FAIL",
    CLEAR_ERROR: "CLEAR_ERROR",
};

export default ActionTypes;